version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./container-data/redis:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data_container:
